### ISSUE TITLE
[功能请求] 将图片以jpg格式保存

### ISSUE THREAD

**Issue by lanyeeee** [lanyeeee/copymanga-downloader#1]
### 原因

从拷贝漫画服务器直接下载到的图片格式为webp，而webp不够通用，有些设备还不支持webp。
为了提高图片的兼容性，希望能够提供将图片下载为jpg的选项。

### 功能简述

希望在下载漫画时，能够选择将图片格式从webp转换为jpg

### 功能逻辑

- 增加一个多选框，允许用户选择是否将图片下载为jpg。
- 如果用户选择下载为jpg，将在下载完成后自动将webp转为jpg。

**Comment by Z-fly** [comment]
可以再增加个选项，下载时候直接转为jpg，不保留webp

**Comment by lanyeeee** [comment]
已在 [v0.2.0](https://github.com/lanyeeee/copymanga-downloader/releases/tag/v0.2.0) 完成
