### ISSUE TITLE
[功能请求] 为下载的章节添加序号

### ISSUE THREAD

**Issue by spr-equinox** [lanyeeee/copymanga-downloader#14]
### 原因

![image](https://github.com/user-attachments/assets/318c21c2-ca1f-4d49-b0b0-8f3927dd5d84)
像这样又有正篇又有特典的漫画下载下来本地顺序是乱的

### 功能简述

。

### 功能逻辑

。

**Comment by lanyeeee** [comment]
已在 [v0.3.2](https://github.com/lanyeeee/copymanga-downloader/releases/tag/v0.3.2) 实现
